### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by gaby** [go-baa/pool#3]
Hello @hengfeiyang What is the status of this project? Are you still making changes or looking for someone to take over?

I'm interested in using this, but there hasnt been any updates in a long time.

Thanks!

**Comment by hengfeiyang** [comment]
Yep, if you have some issue, i will fix it. but this project is very simple, do you have some idea about it?

**Comment by gaby** [comment]
Basically, I'm curious on how this code handles concurrency since it only uses the Mutex during `destroy`. From my unnderstanding for it to be concurrency safe, the Lock would have to be called for each function. 

Adding CI via Github actions would be a plus, also updating any dependencies.

**Comment by hengfeiyang** [comment]
1. it's concurrency safe, we use channel for get / put conn.
2. added CI.
3. updated depends.

Thanks

**Comment by gaby** [comment]
@hengfeiyang Thank you! Looks good!
